# Generated by Django 5.2.13 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entity_size',
            field=models.CharField(blank=True, choices=[('micro', 'Micro'), ('pequena', 'Pequena'), ('media', 'Média'), ('grande', 'Grande')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('empresa', 'Empresa'), ('associacao', 'Associação'), ('municipio', 'Município'), ('ensino', 'Instituição de Ensino'), ('ong', 'ONG'), ('outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_cae',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nuts_ii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nuts_iii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_cae',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sme_certified',
            field=models.BooleanField(default=False),
        ),
    ]
