# Generated by Django 5.2.13 on 2026-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_address_userprofile_entity_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entity_size',
            field=models.CharField(blank=True, choices=[('micro', 'micro'), ('pequena', 'pequena'), ('media', 'media'), ('grande', 'grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('empresa', 'empresa'), ('associacao', 'associacao'), ('municipio', 'municipio'), ('ensino', 'ensino'), ('ong', 'ong'), ('outro', 'outro')], max_length=20, null=True),
        ),
    ]
