# Generated by Django 5.2.13 on 2026-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_entity_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sme_certified',
        ),
    ]
