# Generated by Django 5.2.13 on 2026-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_sme_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('commercial', 'Commercial'), ('composer', 'Composer'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=20),
        ),
    ]
