# Generated by Django 5.2.13 on 2026-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('commercial', 'Commercial'), ('composer', 'Composer'), ('client', 'Client')], db_index=True, default='client', max_length=20),
        ),
    ]
