# Generated by Django 5.2.13 on 2026-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entity_size',
            field=models.CharField(blank=True, choices=[('micro', 'micro'), ('pequena', 'pequena'), ('media', 'media'), ('grande', 'grande')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('empresa', 'empresa'), ('associacao', 'associacao'), ('municipio', 'municipio'), ('ensino', 'ensino'), ('ong', 'ong'), ('outro', 'outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
    ]
