# Generated by Django 5.2.13 on 2026-06-19 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_entity_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_cae',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_cae',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
