# Generated by Django 6.0.4 on 2026-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_capital_userprofile_capital_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
