# Generated by Django 5.2.13 on 2026-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('empresa', 'empresa'), ('associacao', 'associacao'), ('cooperativa', 'cooperativa'), ('fundacao', 'fundacao'), ('municipio', 'municipio'), ('intermunicipio', 'intermunicipio'), ('multimunicipio', 'multimunicipio'), ('junta_freguesia', 'junta_freguesia'), ('misericordia', 'misericordia'), ('ensino', 'ensino'), ('ong', 'ong'), ('outro', 'outro')], max_length=20, null=True),
        ),
    ]
