# Generated by Django 5.2.13 on 2026-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userprofile_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('commercial_grants', 'Commercial Grants'), ('commercial_public', 'Commercial Public'), ('client', 'Client'), ('viewer', 'Viewer')], db_index=True, default='client', max_length=20),
        ),
    ]
