# Generated by Django 5.2.13 on 2026-08-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0029_grant_last_update_source_grant_last_updated_by'),
        ('users', '0017_userprofile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matched_grants',
            field=models.ManyToManyField(blank=True, related_name='matched_by_profiles', to='avisos.grant'),
        ),
    ]
