# Generated by Django 5.2.13 on 2026-09-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_matched_grants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Objetivo do cliente',
                'verbose_name_plural': 'Objetivos do cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
