# Generated by Django 5.2.13 on 2026-09-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.TextField()),
                ('total_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de call',
                'verbose_name_plural': 'Tipos de call',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('total_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa-quadro',
                'verbose_name_plural': 'Programas-quadro',
                'ordering': ['-total_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('31094501', 'Forthcoming'), ('31094502', 'Open')], db_index=True, max_length=20)),
                ('call_identifier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('call_title', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadlines', models.JSONField(blank=True, default=list)),
                ('deadline_model', models.CharField(blank=True, default='', max_length=100)),
                ('programme_period', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('call_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='calls.calltype')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='calls.programmetype')),
            ],
            options={
                'ordering': ['-start_date', 'identifier'],
                'indexes': [models.Index(fields=['status', '-start_date'], name='calls_call_status_2d5c0e_idx'), models.Index(fields=['programme', 'status'], name='calls_call_program_cdd418_idx')],
            },
        ),
    ]
