# Generated by Django 5.2.13 on 2026-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='budget_total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='cross_cutting_priorities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='expected_grants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='max_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='min_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='types_of_action',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
