# Generated by Django 5.2.13 on 2026-09-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_budget_total_call_cross_cutting_priorities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='allow_partner_search',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='ca_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='contract_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='destination',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='destination_group',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='geographical_zones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='mission',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='programme_divisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='project_acronym',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='project_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='specific_objective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.CharField(db_index=True, max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('label', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código traduzido',
                'verbose_name_plural': 'Códigos traduzidos',
                'ordering': ['facet', 'label'],
                'constraints': [models.UniqueConstraint(fields=('facet', 'code'), name='uniq_codelabel_facet_code')],
            },
        ),
    ]
