# Generated by Django 5.2.13 on 2026-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_allow_partner_search_call_ca_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelabel',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
