# Generated by Django 5.2.13 on 2026-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_codelabel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='access_restriction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='api_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='beneficiary_administration_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='budget_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='ccm_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='ccm_tags2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='cen_tags_a',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='cft_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='call',
            name='children',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='closing_date_raw',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='call',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='contract_type_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='corporate_search_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='database',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='database_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='description_byte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='destination_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='destination_description_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='destination_details_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='destination_group_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='enriched_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='call',
            name='es_checksum',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='call',
            name='es_combine',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='es_content_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='es_datasource',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='es_filename',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='es_first_ingest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='es_in_ccm_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='es_in_ccm_tags2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='es_ingest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='es_queue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='es_sort_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='es_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='focus_area',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='further_information_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='geographical_zone_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='group_by_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='highlighted_fragments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='latest_infos_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='links_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='mission_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='mission_group_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='programme_division_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='programme_division_prospect_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='sep_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='sort_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='specific_objective_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='support_info_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='topic_conditions_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='call',
            name='type_of_mgas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='update_date_raw',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='call',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
