# Generated by Django 5.2.13 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_access_restriction_call_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('31094501', 'Forthcoming'), ('31094502', 'Open'), ('31094503', 'Closed')], db_index=True, max_length=20),
        ),
    ]
