# Generated by Django 5.2.13 on 2026-09-18 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_alter_call_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='last_update_source',
            field=models.CharField(choices=[('api', 'API (sync)'), ('manual', 'Manual')], db_index=True, default='api', max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
