# Generated by Django 6.0.4 on 2026-05-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('compete', 'Compete2030'), ('portugal', 'Portugal2030'), ('prr', 'PRR')], db_index=True, max_length=20)),
                ('url_scraping', models.URLField(max_length=500, unique=True)),
                ('caminho_pdf', models.CharField(blank=True, max_length=500)),
                ('caminho_markdown', models.CharField(blank=True, max_length=500)),
                ('processado_ia', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_aviso', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('programa_financiador', models.CharField(blank=True, max_length=300, null=True)),
                ('entidade_gestora', models.CharField(blank=True, max_length=300, null=True)),
                ('data_publicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_republicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_republicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alteracao', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidade_aviso', models.CharField(blank=True, max_length=100, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('nome_fundo', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridade_programa', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_intervencao_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('duracao_maxima_meses', models.IntegerField(blank=True, null=True)),
                ('caes_elegiveis', models.JSONField(blank=True, default=list)),
                ('regioes_admissiveis', models.JSONField(blank=True, default=list)),
                ('data_inicio_elegibilidade_despesa', models.CharField(blank=True, max_length=50, null=True)),
                ('objetivo_especifico', models.TextField(blank=True, null=True)),
                ('tipologia_operacao', models.TextField(blank=True, null=True)),
                ('acoes_abrangidas', models.TextField(blank=True, null=True)),
                ('organismos_intermedios', models.JSONField(blank=True, default=list)),
                ('legislacao_aplicavel', models.JSONField(blank=True, default=list)),
                ('documentos_regulamentacao', models.JSONField(blank=True, default=list)),
                ('setores_tecnologicos_alvo', models.JSONField(blank=True, default=list)),
                ('submissao_candidaturas', models.CharField(blank=True, max_length=300, null=True)),
                ('criterios_elegibilidade_beneficiario', models.JSONField(blank=True, default=list)),
                ('destinatarios_finais', models.JSONField(blank=True, default=list)),
                ('principio_dnsh', models.TextField(blank=True, null=True)),
                ('requisitos_compromisso', models.TextField(blank=True, null=True)),
                ('dotacao_global', models.FloatField(blank=True, null=True)),
                ('territorios_baixa_densidade', models.JSONField(blank=True, default=list)),
                ('limites_submissao', models.TextField(blank=True, null=True)),
                ('data_limite_execucao_absoluta', models.CharField(blank=True, max_length=50, null=True)),
                ('metas_execucao_financeira', models.JSONField(blank=True, default=list)),
                ('investimento_minimo', models.FloatField(blank=True, null=True)),
                ('investimento_maximo', models.FloatField(blank=True, null=True)),
                ('limite_autofinanciamento_exigido', models.FloatField(blank=True, null=True)),
                ('regime_auxilio_estado', models.CharField(blank=True, max_length=300, null=True)),
                ('artigo_rgbc_aplicavel', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.JSONField(blank=True, default=list)),
                ('formas_pagamento', models.JSONField(blank=True, default=list)),
                ('criterios_selecao_projeto', models.JSONField(blank=True, default=list)),
                ('despesas_elegiveis', models.JSONField(blank=True, default=list)),
                ('despesas_nao_elegiveis', models.JSONField(blank=True, default=list)),
                ('indicadores_realizacao', models.JSONField(blank=True, default=list)),
                ('indicadores_resultados', models.JSONField(blank=True, default=list)),
                ('indicadores_acompanhamento', models.JSONField(blank=True, default=list)),
                ('obrigacoes_beneficiarios', models.JSONField(blank=True, default=list)),
                ('obrigacoes_comunicacao', models.JSONField(blank=True, default=list)),
                ('documentos_candidatura', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='AreaAbrangida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.CharField(blank=True, max_length=100, null=True)),
                ('area_geografica', models.CharField(blank=True, max_length=200, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_abrangidas', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Áreas Abrangidas',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entidade', models.CharField(blank=True, max_length=300, null=True)),
                ('dotacao_atribuida', models.FloatField(blank=True, null=True)),
                ('meta_unidades', models.IntegerField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios_alvo', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Beneficiários Alvo',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioPorAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(blank=True, max_length=200, null=True)),
                ('entidades', models.JSONField(blank=True, default=list)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios_por_acao', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Beneficiários por Ação',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fase', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('data_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_fim', models.CharField(blank=True, max_length=50, null=True)),
                ('condicao_acesso', models.TextField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='avisos.aviso')),
            ],
        ),
        migrations.CreateModel(
            name='FaseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fase', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_area', models.CharField(blank=True, max_length=100, null=True)),
                ('dotacao_orcamental', models.FloatField(blank=True, null=True)),
                ('taxa_financiamento_maxima', models.FloatField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase_areas', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Fases por Área',
            },
        ),
        migrations.CreateModel(
            name='LimiteDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_limite', models.CharField(blank=True, max_length=100, null=True)),
                ('rubrica_despesa', models.CharField(blank=True, max_length=300, null=True)),
                ('metodologia_ocs_aplicavel', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_maximo_absoluto', models.FloatField(blank=True, null=True)),
                ('valor_maximo_percentual', models.FloatField(blank=True, null=True)),
                ('base_calculo', models.TextField(blank=True, null=True)),
                ('condicoes_especifica', models.TextField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_despesa', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Limites de Despesa',
            },
        ),
        migrations.CreateModel(
            name='MetodologiaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_avaliacao', models.CharField(blank=True, max_length=100, null=True)),
                ('formula_merito_projeto', models.TextField(blank=True, null=True)),
                ('pontuacao_minima_global', models.FloatField(blank=True, null=True)),
                ('criterios_avaliacao', models.JSONField(blank=True, default=list)),
                ('criterios_desempate', models.JSONField(blank=True, default=list)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodologias_avaliacao', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Metodologias de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='PenalizacaoIncumprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_penalizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_indicadores', models.CharField(blank=True, max_length=200, null=True)),
                ('limiar_tolerancia_geral', models.FloatField(blank=True, null=True)),
                ('limiar_tolerancia_baixa_densidade', models.FloatField(blank=True, null=True)),
                ('reducao_por_ponto_percentual', models.FloatField(blank=True, null=True)),
                ('penalizacao_maxima_percentual', models.FloatField(blank=True, null=True)),
                ('limiar_revogacao_financiamento', models.FloatField(blank=True, null=True)),
                ('descricao_regra', models.TextField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizacoes', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Penalizações por Incumprimento',
            },
        ),
        migrations.CreateModel(
            name='TaxaFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_taxa', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensao_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('regime_auxilio', models.CharField(blank=True, max_length=200, null=True)),
                ('taxa_base', models.CharField(blank=True, max_length=50, null=True)),
                ('majoracao_regional', models.CharField(blank=True, max_length=50, null=True)),
                ('taxa_maxima_global', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_acumulacao_minimis', models.FloatField(blank=True, null=True)),
                ('condicao_especifica', models.TextField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_financiamento', to='avisos.aviso')),
            ],
            options={
                'verbose_name_plural': 'Taxas de Financiamento',
            },
        ),
    ]
