# Generated by Django 5.2.13 on 2026-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaabrangida',
            name='area_geografica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioalvo',
            name='nome_entidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioporacao',
            name='tipo_acao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitedespesa',
            name='metodologia_ocs_aplicavel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitedespesa',
            name='rubrica_despesa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalizacaoincumprimento',
            name='tipo_indicadores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxafinanciamento',
            name='dimensao_empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxafinanciamento',
            name='regime_auxilio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
