# Generated by Django 5.2.13 on 2026-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_areaabrangida_area_geografica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='artigo_rgbc_aplicavel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='entidade_gestora',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='prioridade_programa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='programa_financiador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='regime_auxilio_estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='submissao_candidaturas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='tipo_intervencao_codigo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
