# Generated by Django 5.2.13 on 2026-06-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0003_alter_aviso_artigo_rgbc_aplicavel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeneficiarioAlvo',
        ),
    ]
