# Generated by Django 5.2.13 on 2026-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0004_delete_beneficiarioalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='aprofundar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
