# Generated by Django 5.2.13 on 2026-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_add_aprofundar_to_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaabrangida',
            name='area_geografica',
        ),
        migrations.RemoveField(
            model_name='areaabrangida',
            name='codigo_area',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='acoes_abrangidas',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='aprofundar',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='artigo_rgbc_aplicavel',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='caes_elegiveis',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='codigo_aviso',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='criterios_elegibilidade_beneficiario',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='criterios_selecao_projeto',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_inicio_elegibilidade_despesa',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_limite_execucao_absoluta',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_republicacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='despesas_elegiveis',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='despesas_nao_elegiveis',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='destinatarios_finais',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='documentos_candidatura',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='documentos_regulamentacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='dotacao_global',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='duracao_maxima_meses',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='entidade_gestora',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='formas_pagamento',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='indicadores_acompanhamento',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='indicadores_realizacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='indicadores_resultados',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='investimento_maximo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='investimento_minimo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='legislacao_aplicavel',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='limite_autofinanciamento_exigido',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='limites_submissao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='metas_execucao_financeira',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='modalidade_aviso',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='nome_fundo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='objetivo_especifico',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='obrigacoes_beneficiarios',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='obrigacoes_comunicacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='organismos_intermedios',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='principio_dnsh',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='prioridade_programa',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='programa_financiador',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='regime_auxilio_estado',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='regioes_admissiveis',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='requisitos_compromisso',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='setores_tecnologicos_alvo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='submissao_candidaturas',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='territorios_baixa_densidade',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='tipo_intervencao_codigo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='tipologia_operacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='ultima_republicacao',
        ),
        migrations.RemoveField(
            model_name='beneficiarioporacao',
            name='entidades',
        ),
        migrations.RemoveField(
            model_name='beneficiarioporacao',
            name='tipo_acao',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='codigo_fase',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='condicao_acesso',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='fasearea',
            name='codigo_area',
        ),
        migrations.RemoveField(
            model_name='fasearea',
            name='codigo_fase',
        ),
        migrations.RemoveField(
            model_name='fasearea',
            name='dotacao_orcamental',
        ),
        migrations.RemoveField(
            model_name='fasearea',
            name='taxa_financiamento_maxima',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='base_calculo',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='codigo_limite',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='condicoes_especifica',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='metodologia_ocs_aplicavel',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='rubrica_despesa',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='valor_maximo_absoluto',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='valor_maximo_percentual',
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='codigo_avaliacao',
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='criterios_avaliacao',
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='criterios_desempate',
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='formula_merito_projeto',
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='pontuacao_minima_global',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='codigo_penalizacao',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='descricao_regra',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='limiar_revogacao_financiamento',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='limiar_tolerancia_baixa_densidade',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='limiar_tolerancia_geral',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='penalizacao_maxima_percentual',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='reducao_por_ponto_percentual',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='tipo_indicadores',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='codigo_taxa',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='condicao_especifica',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='dimensao_empresa',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='limite_acumulacao_minimis',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='majoracao_regional',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='regime_auxilio',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='taxa_base',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='taxa_maxima_global',
        ),
        migrations.AddField(
            model_name='areaabrangida',
            name='area_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='areaabrangida',
            name='geographic_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='absolute_execution_deadline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='amendment_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='applicable_gber_article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='applicable_legislation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='application_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='application_submission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='beneficiary_eligibility_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='beneficiary_obligations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='commitment_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='communication_obligations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='contact',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='covered_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='dnsh_principle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='eligible_cae_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='eligible_expenses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='eligible_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='expense_eligibility_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='final_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='financial_execution_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='financing_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='fund_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='ineligible_expenses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='intermediate_bodies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='intervention_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='last_republication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='low_density_territories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='managing_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='max_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='maximum_investment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='minimum_investment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='monitoring_indicators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='notice_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='notice_modality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='operation_typology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='output_indicators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='program_priority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='project_selection_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='publication_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='regulatory_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='republication_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='required_self_financing_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='result_indicators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='specific_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='state_aid_regime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='submission_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='target_technology_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='to_explore',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aviso',
            name='total_allocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioporacao',
            name='action_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioporacao',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fase',
            name='access_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='phase_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fasearea',
            name='area_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fasearea',
            name='budget_allocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasearea',
            name='max_financing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasearea',
            name='phase_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='applicable_ocs_methodology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='calculation_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='expense_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='limit_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='max_absolute_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='max_percentage_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitedespesa',
            name='specific_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodologiaavaliacao',
            name='evaluation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodologiaavaliacao',
            name='evaluation_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metodologiaavaliacao',
            name='min_global_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodologiaavaliacao',
            name='project_merit_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodologiaavaliacao',
            name='tiebreaker_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='compliance_grade_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='financing_revocation_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='general_tolerance_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='indicator_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='low_density_tolerance_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='max_penalty_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='penalty_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='reduction_per_percentage_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalizacaoincumprimento',
            name='rule_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='aid_regime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='base_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='company_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='max_global_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='minimis_accumulation_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='rate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='regional_bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxafinanciamento',
            name='specific_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
