# Generated by Django 5.2.13 on 2026-06-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0006_rename_fields_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('compete', 'Compete2030'), ('portugal', 'Portugal2030'), ('prr', 'PRR')], db_index=True, max_length=20)),
                ('url_scraping', models.URLField(max_length=500, unique=True)),
                ('caminho_pdf', models.CharField(blank=True, max_length=500)),
                ('caminho_markdown', models.CharField(blank=True, max_length=500)),
                ('processado_ia', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grant_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('financing_program', models.TextField(blank=True, null=True)),
                ('managing_entity', models.TextField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('republication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_republication', models.CharField(blank=True, max_length=50, null=True)),
                ('amendment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('notice_modality', models.CharField(blank=True, max_length=100, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('fund_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program_priority', models.TextField(blank=True, null=True)),
                ('intervention_type_code', models.TextField(blank=True, null=True)),
                ('max_duration_months', models.IntegerField(blank=True, null=True)),
                ('eligible_cae_codes', models.JSONField(blank=True, default=list)),
                ('eligible_regions', models.JSONField(blank=True, default=list)),
                ('expense_eligibility_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('specific_objective', models.TextField(blank=True, null=True)),
                ('operation_typology', models.TextField(blank=True, null=True)),
                ('covered_actions', models.TextField(blank=True, null=True)),
                ('intermediate_bodies', models.JSONField(blank=True, default=list)),
                ('applicable_legislation', models.JSONField(blank=True, default=list)),
                ('regulatory_documents', models.JSONField(blank=True, default=list)),
                ('target_technology_sectors', models.JSONField(blank=True, default=list)),
                ('application_submission', models.TextField(blank=True, null=True)),
                ('beneficiary_eligibility_criteria', models.JSONField(blank=True, default=list)),
                ('final_recipients', models.JSONField(blank=True, default=list)),
                ('dnsh_principle', models.TextField(blank=True, null=True)),
                ('commitment_requirements', models.TextField(blank=True, null=True)),
                ('total_allocation', models.FloatField(blank=True, null=True)),
                ('low_density_territories', models.JSONField(blank=True, default=list)),
                ('submission_limits', models.TextField(blank=True, null=True)),
                ('absolute_execution_deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_execution_targets', models.JSONField(blank=True, default=list)),
                ('minimum_investment', models.FloatField(blank=True, null=True)),
                ('maximum_investment', models.FloatField(blank=True, null=True)),
                ('required_self_financing_limit', models.FloatField(blank=True, null=True)),
                ('state_aid_regime', models.TextField(blank=True, null=True)),
                ('applicable_gber_article', models.TextField(blank=True, null=True)),
                ('contact', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('project_selection_criteria', models.JSONField(blank=True, default=list)),
                ('eligible_expenses', models.JSONField(blank=True, default=list)),
                ('ineligible_expenses', models.JSONField(blank=True, default=list)),
                ('output_indicators', models.JSONField(blank=True, default=list)),
                ('result_indicators', models.JSONField(blank=True, default=list)),
                ('monitoring_indicators', models.JSONField(blank=True, default=list)),
                ('beneficiary_obligations', models.JSONField(blank=True, default=list)),
                ('communication_obligations', models.JSONField(blank=True, default=list)),
                ('application_documents', models.JSONField(blank=True, default=list)),
                ('to_explore', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='metodologiaavaliacao',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='fasearea',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='taxafinanciamento',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='beneficiarioporacao',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='limitedespesa',
            name='aviso',
        ),
        migrations.RemoveField(
            model_name='penalizacaoincumprimento',
            name='aviso',
        ),
        migrations.CreateModel(
            name='FinancingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.TextField(blank=True, null=True)),
                ('aid_regime', models.TextField(blank=True, null=True)),
                ('base_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('regional_bonus', models.CharField(blank=True, max_length=50, null=True)),
                ('max_global_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('minimis_accumulation_limit', models.FloatField(blank=True, null=True)),
                ('specific_condition', models.TextField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_rates', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_category', models.TextField(blank=True, null=True)),
                ('applicable_ocs_methodology', models.TextField(blank=True, null=True)),
                ('max_absolute_value', models.FloatField(blank=True, null=True)),
                ('max_percentage_value', models.FloatField(blank=True, null=True)),
                ('calculation_base', models.TextField(blank=True, null=True)),
                ('specific_conditions', models.TextField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_limits', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('project_merit_formula', models.TextField(blank=True, null=True)),
                ('min_global_score', models.FloatField(blank=True, null=True)),
                ('evaluation_criteria', models.JSONField(blank=True, default=list)),
                ('tiebreaker_criteria', models.JSONField(blank=True, default=list)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_methodologies', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(blank=True, max_length=100, null=True)),
                ('geographic_area', models.TextField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_areas', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryByAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.TextField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries_by_action', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='NonCompliancePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_code', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_types', models.TextField(blank=True, null=True)),
                ('compliance_grade_formula', models.TextField(blank=True, null=True)),
                ('general_tolerance_threshold', models.FloatField(blank=True, null=True)),
                ('low_density_tolerance_threshold', models.FloatField(blank=True, null=True)),
                ('reduction_per_percentage_point', models.FloatField(blank=True, null=True)),
                ('max_penalty_percentage', models.FloatField(blank=True, null=True)),
                ('financing_revocation_threshold', models.FloatField(blank=True, null=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_compliance_penalties', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('access_condition', models.TextField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='avisos.grant')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.CharField(blank=True, max_length=100, null=True)),
                ('area_code', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_allocation', models.FloatField(blank=True, null=True)),
                ('max_financing_rate', models.FloatField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_areas', to='avisos.grant')),
            ],
        ),
        migrations.DeleteModel(
            name='AreaAbrangida',
        ),
        migrations.DeleteModel(
            name='MetodologiaAvaliacao',
        ),
        migrations.DeleteModel(
            name='FaseArea',
        ),
        migrations.DeleteModel(
            name='TaxaFinanciamento',
        ),
        migrations.DeleteModel(
            name='BeneficiarioPorAcao',
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
        migrations.DeleteModel(
            name='LimiteDespesa',
        ),
        migrations.DeleteModel(
            name='Aviso',
        ),
        migrations.DeleteModel(
            name='PenalizacaoIncumprimento',
        ),
    ]
