# Generated by Django 5.2.13 on 2026-06-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0007_rename_classes_to_english'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='processado_ia',
            new_name='ai_processed',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='caminho_markdown',
            new_name='markdown_path',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='caminho_pdf',
            new_name='pdf_path',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='url_scraping',
            new_name='scraping_url',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='origem',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
    ]
