# Generated by Django 5.2.13 on 2026-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0009_add_grant_document_and_coverage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingrate',
            name='base_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financingrate',
            name='max_global_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financingrate',
            name='regional_bonus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='absolute_execution_deadline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amendment_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='expense_eligibility_start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='last_republication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='republication_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
