# Generated by Django 6.0.4 on 2026-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0011_alter_coveredarea_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='closing_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='opening_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
