# Generated by Django 6.0.4 on 2026-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0012_grant_closing_date_grant_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='excluded_caes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grant',
            name='included_caes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
