# Generated by Django 6.0.4 on 2026-06-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0013_grant_excluded_caes_grant_included_caes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='eligible_cae_codes',
        ),
    ]
