# Generated by Django 6.0.4 on 2026-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0014_remove_grant_eligible_cae_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='admissibility_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grant',
            name='operation_eligibility_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
