# Generated by Django 6.0.4 on 2026-07-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0015_grant_admissibility_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmethodology',
            name='scoring_scale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phasearea',
            name='fund_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
