# Generated by Django 6.0.4 on 2026-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0016_evaluationmethodology_scoring_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='activity_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='activity_embedding_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
