# Generated by Django 6.0.4 on 2026-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0017_grant_activity_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncompliancepenalty',
            name='penalty_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='grant',
            name='activity_embedding_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fund_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='notice_modality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='source',
            field=models.CharField(choices=[('compete', 'Compete2030'), ('portugal', 'Portugal2030'), ('prr', 'PRR')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grantdocument',
            name='doc_type',
            field=models.CharField(choices=[('base', 'Base'), ('republication', 'Republicação'), ('amendment', 'Alteração'), ('prorrogation', 'Prorrogação'), ('rectification', 'Retificação'), ('annex', 'Anexo'), ('other', 'Outro')], db_index=True, default='other', max_length=200),
        ),
        migrations.AlterField(
            model_name='noncompliancepenalty',
            name='penalty_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phasearea',
            name='fund_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
