# Generated by Django 6.0.4 on 2026-07-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0018_noncompliancepenalty_penalty_tiers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveredarea',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='evaluationmethodology',
            name='evaluation_code',
        ),
        migrations.RemoveField(
            model_name='expenselimit',
            name='limit_code',
        ),
        migrations.RemoveField(
            model_name='financingrate',
            name='rate_code',
        ),
        migrations.RemoveField(
            model_name='noncompliancepenalty',
            name='penalty_code',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='phase_code',
        ),
        migrations.RemoveField(
            model_name='phasearea',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='phasearea',
            name='phase_code',
        ),
        migrations.AddField(
            model_name='phasearea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_areas', to='avisos.coveredarea'),
        ),
        migrations.AddField(
            model_name='phasearea',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_areas', to='avisos.phase'),
        ),
    ]
