# Generated by Django 6.0.4 on 2026-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0019_remove_coveredarea_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasearea',
            name='distribution',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
