# Generated by Django 6.0.4 on 2026-07-08 16:28

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0020_phasearea_distribution'),
    ]

    operations = [
        # Extensão pgvector (idempotente). Necessária antes de qualquer coluna `vector`.
        VectorExtension(),
        # activity_embedding era JSONField (cache descartável) — jsonb→vector não faz cast
        # automático, por isso remove-se e recria-se como vector (embeddings recalculam-se).
        migrations.RemoveField(model_name='grant', name='activity_embedding'),
        migrations.AddField(
            model_name='grant',
            name='activity_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
