# Generated by Django 5.2.13 on 2026-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0021_alter_grant_activity_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='annex_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
