# Generated by Django 5.2.13 on 2026-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0022_grant_annex_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
