# Generated by Django 5.2.13 on 2026-07-16 10:31

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0024_rename_self_financing_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_type', models.CharField(choices=[('GENERAL', 'Geral (conteúdo do aviso)'), ('SECTOR', 'Setorial (domínio tecnológico/económico)')], db_index=True, max_length=32)),
                ('model', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('text_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='avisos.grant')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='grant_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('grant', 'embedding_type'), name='uniq_grant_embedding_per_type')],
            },
        ),
    ]
