# Generated by Django 5.2.13 on 2026-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0025_grantembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='financing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
