# Generated by Django 5.2.13 on 2026-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0026_grant_financing_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('kind', models.CharField(choices=[('included', 'included'), ('excluded', 'excluded')], max_length=8)),
            ],
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(condition=models.Q(('active', True), ('ai_processed', True)), fields=['id'], name='grant_active_processed_idx'),
        ),
        migrations.AddField(
            model_name='grantcae',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cae_entries', to='avisos.grant'),
        ),
        migrations.AddIndex(
            model_name='grantcae',
            index=models.Index(fields=['prefix', 'kind'], name='avisos_gran_prefix_720543_idx'),
        ),
    ]
