# Generated by Django 5.2.13 on 2026-07-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0028_populate_grant_cae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='last_update_source',
            field=models.CharField(choices=[('scrape', 'Scrape/IA'), ('manual', 'Manual')], db_index=True, default='scrape', max_length=10),
        ),
        migrations.AddField(
            model_name='grant',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
