# Generated by Django 5.2.13 on 2026-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(unique=True)),
                ('beneficiary_type', models.TextField(blank=True, default='')),
                ('grant_type', models.TextField(blank=True, default='')),
                ('designation', models.TextField(blank=True, default='')),
                ('programme', models.TextField(blank=True, default='')),
                ('specific_objective', models.TextField(blank=True, default='')),
                ('fund', models.TextField(blank=True, default='')),
                ('total_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expected_start', models.DateField(blank=True, null=True)),
                ('expected_end', models.DateField(blank=True, null=True)),
                ('quadrimester', models.CharField(blank=True, default='', max_length=50)),
                ('nuts', models.TextField(blank=True, default='')),
                ('submission_mode', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expected_start', 'plan_id'],
            },
        ),
    ]
