# Generated by Django 6.0.4 on 2026-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_incm', models.CharField(max_length=20, unique=True, verbose_name='ID INCM')),
                ('n_anuncio', models.CharField(blank=True, max_length=20, verbose_name='Número do Anúncio')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('nif_entidade', models.CharField(blank=True, max_length=9, verbose_name='NIF da Entidade')),
                ('designacao_entidade', models.CharField(blank=True, max_length=255, verbose_name='Designação da Entidade')),
                ('descricao_anuncio', models.TextField(blank=True, verbose_name='Descrição do Anúncio')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL do Anúncio')),
                ('num_dr', models.CharField(blank=True, max_length=10, verbose_name='Número DR')),
                ('serie', models.CharField(blank=True, max_length=5, verbose_name='Série')),
                ('tipo_acto', models.CharField(blank=True, choices=[('Anúncio de procedimento', 'Anúncio de procedimento'), ('Anúncio de concurso urgente', 'Anúncio de concurso urgente'), ('Declaração de retificação de anúncio', 'Declaração de retificação de anúncio'), ('Aviso de prorrogação de prazo', 'Aviso de prorrogação de prazo'), ('Anúncio de Alteração', 'Anúncio de Alteração')], max_length=100, verbose_name='Tipo de Acto')),
                ('tipos_contrato', models.JSONField(blank=True, default=list, verbose_name='Tipos de Contrato')),
                ('cpvs', models.JSONField(blank=True, default=list, verbose_name='CPVs')),
                ('lotes', models.JSONField(blank=True, default=list, verbose_name='Lotes')),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço Base')),
                ('modelo_anuncio', models.CharField(blank=True, choices=[('Concurso público', 'Concurso público'), ('Concurso público urgente', 'Concurso público urgente'), ('Concurso limitado por prévia qualificação', 'Concurso limitado por prévia qualificação'), ('Procedimento de negociação', 'Procedimento de negociação'), ('Diálogo concorrencial', 'Diálogo concorrencial'), ('Concurso de concepção', 'Concurso de concepção'), ('Anúncio simplificado', 'Anúncio simplificado'), ('Instituição de sistema de qualificação', 'Instituição de sistema de qualificação'), ('Intenção de celebração de empreitadas de obras publicas por concessionários que não sejam entidades adjudicantes', 'Intenção de celebração de empreitadas de obras publicas por concessionários que não sejam entidades adjudicantes'), ('Parceria para a inovação', 'Parceria para a inovação'), ('Concurso de ideias', 'Concurso de ideias'), ('Instituição de sistema de aquisição dinâmico', 'Instituição de sistema de aquisição dinâmico'), ('Hasta Pública de Alienação de Bens Móveis', 'Hasta Pública de Alienação de Bens Móveis'), ('Aquisição de Serviços Sociais e de Outros Serviços Específicos', 'Aquisição de Serviços Sociais e de Outros Serviços Específicos'), ('Anúncio de Adjudicação de Aquisição de Serviços Sociais e de Outros Serviços Específicos', 'Anúncio de Adjudicação de Aquisição de Serviços Sociais e de Outros Serviços Específicos'), ('Concurso público simplificado', 'Concurso público simplificado'), ('Concurso limitado por prévia qualificação simplificado', 'Concurso limitado por prévia qualificação simplificado')], max_length=255, verbose_name='Modelo de Anúncio')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('criter_ambient', models.BooleanField(default=False, verbose_name='Critério Ambiental')),
                ('prazo_propostas', models.IntegerField(blank=True, null=True, verbose_name='Prazo de Propostas (dias)')),
                ('pecas_procedimento', models.URLField(blank=True, max_length=500, verbose_name='Peças do Procedimento (URL)')),
                ('data_limite_proposta', models.DateField(blank=True, null=True, verbose_name='Data Limite para Propostas')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
