# Generated by Django 6.0.4 on 2026-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='caderno_encargos_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Caderno de Encargos (caminho local)'),
        ),
    ]
