# Generated by Django 6.0.4 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_caderno_encargos_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='id_incm',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID INCM'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='n_anuncio',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do Anúncio'),
        ),
    ]
