# Generated by Django 6.0.4 on 2026-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_anuncio_id_incm_alter_anuncio_n_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='data_limite_proposta',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite Propostas'),
        ),
    ]
