# Generated by Django 6.0.4 on 2026-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_translate_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='act_type',
            field=models.CharField(blank=True, choices=[('Anúncio de procedimento', 'Anúncio de procedimento'), ('Anúncio de concurso urgente', 'Anúncio de concurso urgente'), ('Declaração de retificação de anúncio', 'Declaração de retificação de anúncio'), ('Aviso de prorrogação de prazo', 'Aviso de prorrogação de prazo'), ('Anúncio de Alteração', 'Anúncio de Alteração')], max_length=100, verbose_name='Act Type'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='contract_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Contract Types'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='dr_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='DR Number'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='entity_nif',
            field=models.CharField(blank=True, max_length=9, verbose_name='Entity Tax ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='environmental_criteria',
            field=models.BooleanField(default=False, verbose_name='Environmental Criteria'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='incm_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='INCM ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='lots',
            field=models.JSONField(blank=True, default=list, verbose_name='Lots'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Notice Number'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='procedure_documents_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Procedure Documents (URL)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='procedure_type',
            field=models.CharField(blank=True, choices=[('Concurso público', 'Concurso público'), ('Concurso público urgente', 'Concurso público urgente'), ('Concurso limitado por prévia qualificação', 'Concurso limitado por prévia qualificação'), ('Procedimento de negociação', 'Procedimento de negociação'), ('Diálogo concorrencial', 'Diálogo concorrencial'), ('Concurso de concepção', 'Concurso de concepção'), ('Anúncio simplificado', 'Anúncio simplificado'), ('Instituição de sistema de qualificação', 'Instituição de sistema de qualificação'), ('Intenção de celebração de empreitadas de obras publicas por concessionários que não sejam entidades adjudicantes', 'Intenção de celebração de empreitadas de obras publicas por concessionários que não sejam entidades adjudicantes'), ('Parceria para a inovação', 'Parceria para a inovação'), ('Concurso de ideias', 'Concurso de ideias'), ('Instituição de sistema de aquisição dinâmico', 'Instituição de sistema de aquisição dinâmico'), ('Hasta Pública de Alienação de Bens Móveis', 'Hasta Pública de Alienação de Bens Móveis'), ('Aquisição de Serviços Sociais e de Outros Serviços Específicos', 'Aquisição de Serviços Sociais e de Outros Serviços Específicos'), ('Anúncio de Adjudicação de Aquisição de Serviços Sociais e de Outros Serviços Específicos', 'Anúncio de Adjudicação de Aquisição de Serviços Sociais e de Outros Serviços Específicos'), ('Concurso público simplificado', 'Concurso público simplificado'), ('Concurso limitado por prévia qualificação simplificado', 'Concurso limitado por prévia qualificação simplificado')], max_length=255, verbose_name='Procedure Type'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='proposal_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Proposal Deadline'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='proposal_period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proposal Period (days)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='series',
            field=models.CharField(blank=True, max_length=5, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='specifications_path',
            field=models.CharField(blank=True, default='', help_text='Local path (under pdf_Anuncios/) of the tender specifications PDF. Can be added/edited/removed manually.', max_length=500, verbose_name='Tender Specifications (local path)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Notice URL'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
