# Generated by Django 6.0.4 on 2026-07-08 16:28

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_notice_act_type_alter_notice_active_and_more'),
    ]

    operations = [
        # Extensão pgvector (idempotente) — antes de qualquer coluna `vector`.
        VectorExtension(),
        migrations.AddField(
            model_name='notice',
            name='activity_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='activity_embedding_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
