# Generated by Django 5.2.13 on 2026-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('to_fix', 'Corrigir')], db_index=True, default='active', max_length=10, verbose_name='Status'),
        ),
    ]
