# Generated by Django 5.2.13 on 2026-07-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0010_alter_notice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='program_path',
            field=models.CharField(blank=True, default='', help_text='Local path (under pdf_Anuncios/) of the competition program (Programa de Concurso) PDF. Can be added/edited/removed manually.', max_length=500, verbose_name='Competition Program (local path)'),
        ),
    ]
