# Generated by Django 5.2.13 on 2026-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_notice_program_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='specifications_ai_status',
            field=models.CharField(blank=True, choices=[('pending', 'Nunca gerado'), ('generating', 'A gerar'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', help_text='Background AI-detail generation status.', max_length=10, verbose_name='Tender Specifications (AI status)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='specifications_description',
            field=models.TextField(blank=True, default='', help_text="Cached AI-generated detailed description of the tender's object/scope.", verbose_name='Tender Specifications (AI description)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='specifications_evaluation',
            field=models.JSONField(blank=True, default=dict, help_text='Cached AI-extracted evaluation criteria (criterios: nome/ponderacao/subcriterios) and scoring formula, as written in the document.', verbose_name='Tender Specifications (AI evaluation)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='specifications_markdown_path',
            field=models.CharField(blank=True, default='', help_text='Local path (under output/markdown/) of the tender specifications converted to markdown. Generated on first AI-detail request.', max_length=500, verbose_name='Tender Specifications (markdown path)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='specifications_observations',
            field=models.JSONField(blank=True, default=list, help_text="Cached AI-generated list of notes (deadlines, guarantees, site visits, etc.) that don't fit the description/evaluation fields.", verbose_name='Tender Specifications (AI observations)'),
        ),
    ]
