# Generated by Django 6.0.4 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NifCompany',
            fields=[
                ('nif', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('locality', models.CharField(blank=True, default='', max_length=255)),
                ('municipality', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('operating_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Proveitos Operacionais EUR (annual turnover) — last available year.', max_digits=18, null=True)),
                ('last_year', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'NIF enrichment',
                'verbose_name_plural': 'NIF enrichment',
            },
        ),
    ]
