# Generated by Django 6.0.4 on 2026-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifcompany',
            name='dimension',
            field=models.CharField(blank=True, choices=[('micro', 'micro'), ('pequena', 'pequena'), ('media', 'media'), ('grande', 'grande')], db_index=True, max_length=10, null=True),
        ),
    ]
